// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "ISD Team",
            "email": "sd.team.sgcu@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/refreshToken": {
            "post": {
                "description": "Return the credential",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh token",
                "parameters": [
                    {
                        "description": "refreshToken request dto",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Credential"
                        }
                    },
                    "400": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "401": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseUnauthorizedErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        },
        "/v1/auth/signin": {
            "post": {
                "description": "Return the credential of user including access token and refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign in user",
                "parameters": [
                    {
                        "description": "signIn request dto",
                        "name": "signIn",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.Credential"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "403": {
                        "description": "Incorrect email or password",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseForbiddenErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        },
        "/v1/auth/signout": {
            "post": {
                "description": "Return the bool value of success",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign out user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SignOutResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseUnauthorizedErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        },
        "/v1/auth/signup": {
            "post": {
                "description": "Return the data of user if successfully",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Signup user",
                "parameters": [
                    {
                        "description": "signup request dto",
                        "name": "signup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SignupResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "409": {
                        "description": "Duplicate email",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseConflictErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        },
        "/v1/likes/": {
            "get": {
                "description": "Return dto.ResponseSuccess",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "like"
                ],
                "summary": "find likes by user id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "404": {
                        "description": "user not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseNotfoundErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            },
            "post": {
                "description": "Return dto.ResponseSuccess",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "like"
                ],
                "summary": "create like",
                "parameters": [
                    {
                        "description": "create like request",
                        "name": "create",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateLikeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            },
            "delete": {
                "description": "Return dto.ResponseSuccess if like is successfully deleted",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "like"
                ],
                "summary": "delete like",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "404": {
                        "description": "like not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseNotfoundErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        },
        "/v1/pets/": {
            "get": {
                "description": "Return the data of pets if successfully",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "find all pets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            },
            "put": {
                "description": "Return the status true of pet if successfully else false",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "change view pet",
                "parameters": [
                    {
                        "description": "change view pet dto",
                        "name": "changeView",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangeViewPetRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "pet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "404": {
                        "description": "Pet not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseNotfoundErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            },
            "delete": {
                "description": "Return the status true of pet if successfully else false",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "delete pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        },
        "/v1/pets/create": {
            "post": {
                "description": "Return the data of pet if successfully",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "create pet",
                "parameters": [
                    {
                        "description": "pet dto",
                        "name": "create",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        },
        "/v1/pets/{id}": {
            "get": {
                "description": "Return the data of pets if successfully",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "find one pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "404": {
                        "description": "Pet not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseNotfoundErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            },
            "put": {
                "description": "Return the data of pet if successfully",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "update pet",
                "parameters": [
                    {
                        "description": "update pet dto",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePetRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "pet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "404": {
                        "description": "Pet not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseNotfoundErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        },
        "/v1/pets/{id}/adopt": {
            "put": {
                "description": "Return true if the pet is successfully adopted",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "Adopt a pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User ID",
                        "name": "user_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Pet ID",
                        "name": "pet_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBadRequestErr"
                        }
                    },
                    "404": {
                        "description": "Pet not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseNotfoundErr"
                        }
                    },
                    "500": {
                        "description": "Internal service error",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseInternalErr"
                        }
                    },
                    "503": {
                        "description": "Service is down",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseServiceDownErr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BadReqErrResponse": {
            "type": "object",
            "properties": {
                "failed_field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "dto.ChangeViewPetRequest": {
            "type": "object",
            "required": [
                "visible"
            ],
            "properties": {
                "visible": {
                    "type": "boolean"
                }
            }
        },
        "dto.CreateLikeRequest": {
            "type": "object",
            "required": [
                "pet_id",
                "user_id"
            ],
            "properties": {
                "pet_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreatePetRequest": {
            "type": "object"
        },
        "dto.Credential": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3BiZX..."
                },
                "expires_in": {
                    "type": "integer",
                    "example": 3600
                },
                "refresh_token": {
                    "type": "string",
                    "example": "e7e84d54-7518-4..."
                }
            }
        },
        "dto.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.ResponseBadRequestErr": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.BadReqErrResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Invalid request body"
                },
                "status_code": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "dto.ResponseConflictErr": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Conflict"
                },
                "status_code": {
                    "type": "integer",
                    "example": 409
                }
            }
        },
        "dto.ResponseForbiddenErr": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Insufficiency permission"
                },
                "status_code": {
                    "type": "integer",
                    "example": 403
                }
            }
        },
        "dto.ResponseInternalErr": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Internal service error"
                },
                "status_code": {
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "dto.ResponseNotfoundErr": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Not found"
                },
                "status_code": {
                    "type": "integer",
                    "example": 404
                }
            }
        },
        "dto.ResponseServiceDownErr": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Service is down"
                },
                "status_code": {
                    "type": "integer",
                    "example": 503
                }
            }
        },
        "dto.ResponseSuccess": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "status_code": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "dto.ResponseUnauthorizedErr": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Invalid token"
                },
                "status_code": {
                    "type": "integer",
                    "example": 401
                }
            }
        },
        "dto.SignInRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 6
                }
            }
        },
        "dto.SignOutResponse": {
            "type": "object",
            "properties": {
                "is_success": {
                    "type": "boolean"
                }
            }
        },
        "dto.SignupRequest": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 6
                }
            }
        },
        "dto.SignupResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                }
            }
        },
        "dto.UpdatePetRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "adopt_by": {
                    "type": "string"
                },
                "background": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "caption": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "habit": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_club_pet": {
                    "type": "boolean"
                },
                "is_sterile": {
                    "type": "boolean"
                },
                "is_vaccinated": {
                    "type": "boolean"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "species": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AuthToken": {
            "description": "Description for what is this security definition being used",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "# Auth Tag API Documentation\n**Auth** functions goes here",
            "name": "auth"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"https", "http"},
	Title:            "JohnJud API",
	Description:      "# Johnjud API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
