version: "3.9"

services:
  local-auth:
    image: ghcr.io/isd-sgcu/johnjud-auth
    container_name: auth
    depends_on:
      - local-db
      - local-cache
    restart: unless-stopped
    environment:
      - APP_PORT=3002
      - APP_ENV=development
      - APP_SECRET=secret
      - DB_URL=postgres://root:root@local-db:5432/johnjud_db
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=3600
      - JWT_REFRESH_TOKEN_TTL=604800
      - JWT_ISSUER=issuer
      - JWT_RESET_TOKEN_TTL=900
      - REDIS_HOST=local-cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - AUTH_CLIENT_URL=http://localhost:3000
      - SENDGRID_API_KEY=api_key
      - SENDGRID_NAME=johnjud
      - SENDGRID_ADDRESS=johnjud@gmail.com
    networks:
      - johnjud-local
      - database
    ports:
      - "3002:3002"

  local-backend:
    image: ghcr.io/isd-sgcu/johnjud-backend
    container_name: backend
    depends_on:
      - local-db
      - local-cache
    restart: unless-stopped
    environment:
      - APP_PORT=3003
      - APP_ENV=development
      - DB_URL=postgres://root:root@local-db:5432/johnjud_db
      - SERVICE_FILE=file:3004
    networks:
      - johnjud-local
      - database
    ports:
      - "3003:3003"

  local-file:
    image: ghcr.io/isd-sgcu/johnjud-file
    container_name: file
    depends_on:
      - local-db
      - local-cache
    restart: unless-stopped
    environment:
      - APP_PORT=3004
      - APP_ENV=production
      - DB_URL=postgres://root:root@local-db:5432/johnjud_db
      - BUCKET_ENDPOINT=minio-api.isd.sgcu.in.th
      - BUCKET_ACCESS_KEY=BUCKET_ACCESS_KEY
      - BUCKET_SECRET_KEY=BUCKET_SECRET_KEY
      - BUCKET_NAME=johnjud-pet-images
      - BUCKET_USE_SSL=true
    networks:
      - johnjud-local
      - database
    ports:
      - "3004:3004"

  local-db:
    image: postgres:15.1-alpine3.17
    container_name: local-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: johnjud_db
    networks:
      - database
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  local-cache:
    image: redis:7.2.3-alpine
    container_name: local-cache
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - database
    ports:
      - "6379:6379"

networks:
  johnjud-local:
    name: johnjud-local
  database:
    name: database
