// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/image/image.service.go

// Package mock_image is a generated GoMock package.
package mock_image

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/isd-sgcu/johnjud-gateway/internal/dto"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AssignPet mocks base method.
func (m *MockService) AssignPet(request *dto.AssignPetRequest) (*dto.AssignPetResponse, *dto.ResponseErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPet", request)
	ret0, _ := ret[0].(*dto.AssignPetResponse)
	ret1, _ := ret[1].(*dto.ResponseErr)
	return ret0, ret1
}

// AssignPet indicates an expected call of AssignPet.
func (mr *MockServiceMockRecorder) AssignPet(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPet", reflect.TypeOf((*MockService)(nil).AssignPet), request)
}

// Delete mocks base method.
func (m *MockService) Delete(id string) (*dto.DeleteImageResponse, *dto.ResponseErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*dto.DeleteImageResponse)
	ret1, _ := ret[1].(*dto.ResponseErr)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), id)
}

// DeleteByPetId mocks base method.
func (m *MockService) DeleteByPetId(petID string) (*dto.DeleteImageResponse, *dto.ResponseErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPetId", petID)
	ret0, _ := ret[0].(*dto.DeleteImageResponse)
	ret1, _ := ret[1].(*dto.ResponseErr)
	return ret0, ret1
}

// DeleteByPetId indicates an expected call of DeleteByPetId.
func (mr *MockServiceMockRecorder) DeleteByPetId(petID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPetId", reflect.TypeOf((*MockService)(nil).DeleteByPetId), petID)
}

// FindAll mocks base method.
func (m *MockService) FindAll() ([]*dto.ImageResponse, *dto.ResponseErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*dto.ImageResponse)
	ret1, _ := ret[1].(*dto.ResponseErr)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockServiceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockService)(nil).FindAll))
}

// FindByPetId mocks base method.
func (m *MockService) FindByPetId(petID string) ([]*dto.ImageResponse, *dto.ResponseErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPetId", petID)
	ret0, _ := ret[0].([]*dto.ImageResponse)
	ret1, _ := ret[1].(*dto.ResponseErr)
	return ret0, ret1
}

// FindByPetId indicates an expected call of FindByPetId.
func (mr *MockServiceMockRecorder) FindByPetId(petID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPetId", reflect.TypeOf((*MockService)(nil).FindByPetId), petID)
}

// Upload mocks base method.
func (m *MockService) Upload(request *dto.UploadImageRequest) (*dto.ImageResponse, *dto.ResponseErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", request)
	ret0, _ := ret[0].(*dto.ImageResponse)
	ret1, _ := ret[1].(*dto.ResponseErr)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockServiceMockRecorder) Upload(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockService)(nil).Upload), request)
}
